spring.application.name=training-system-backend
spring.datasource.url=jdbc:mysql://localhost:3306/training_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=wasana25
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=5000